on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: copilot
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install @azure/mcp (Linux) globally from tgz
        run: npm install -g ./.build/testing.tgz

      - name: Verify @azure/mcp is available
        run: |
          npx @azure/mcp --version

      - name: Log @azure/mcp installed path
        run: |
          npm list -g --depth=0 | grep '@azure/mcp' || echo "@azure/mcp not found in global npm list"
          npm root -g